import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export function jsonToCsv(items: Record<string, unknown>[], headers: string[], keys: string[]): string {
  const csvRows = [];
  
  csvRows.push(headers.join(","));
  
  for (const row of items) {
    const values = keys.map(k => {
      const escaped = ('' + (row[k] ?? '')).replace(/"/g, '\\"');
      return `"${escaped}"`;
    });
    csvRows.push(values.join(","));
  }
  
  return csvRows.join("\n");
}

export async function generateAnalyticsPdf(restaurant: any, data: any): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.276, 841.890]); // A4 Size
  const { width, height } = page.getSize();
  
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  // Brand Color or fallback (red)
  const primaryColor = rgb(0.99, 0.3, 0.24); // #FF4D3D
  const darkColor = rgb(0.09, 0.09, 0.1);
  const lightColor = rgb(0.95, 0.95, 0.96);
  const borderLight = rgb(0.85, 0.85, 0.85);

  // Top header block
  page.drawRectangle({
    x: 0,
    y: height - 120,
    width,
    height: 120,
    color: primaryColor,
  });

  // Header Title
  page.drawText('MONTHLY PERFORMANCE REPORT', {
    x: 40,
    y: height - 60,
    size: 20,
    font: boldFont,
    color: rgb(1, 1, 1),
  });

  page.drawText(`${restaurant.name || 'ScanBite Outlet'}`, {
    x: 40,
    y: height - 85,
    size: 14,
    font: regularFont,
    color: rgb(1, 1, 1),
  });

  page.drawText(`Date: ${new Date().toLocaleDateString('en-IN')}`, {
    x: width - 180,
    y: height - 85,
    size: 11,
    font: boldFont,
    color: rgb(1, 1, 1),
  });

  // KPI Overview Section
  page.drawText('KEY PERFORMANCE INDICATORS', {
    x: 40,
    y: height - 165,
    size: 12,
    font: boldFont,
    color: darkColor,
  });

  // Render KPI boxes in 2x2 grid
  const kpis = [
    { label: 'TOTAL REVENUE', value: `INR ${data.totalRevenue?.toLocaleString('en-IN') || '0.00'}` },
    { label: 'TOTAL ORDERS', value: `${data.totalOrders || 0}` },
    { label: 'AVERAGE ORDER VALUE', value: `INR ${data.averageOrderValue?.toLocaleString('en-IN') || '0.00'}` },
    { label: 'UNIQUE CUSTOMERS', value: `${data.uniqueCustomers || 0}` },
  ];

  let kpiY = height - 260;
  for (let i = 0; i < kpis.length; i++) {
    const kpi = kpis[i];
    const isLeft = i % 2 === 0;
    const boxX = isLeft ? 40 : width / 2 + 10;
    const boxY = isLeft ? kpiY : kpiY;
    
    page.drawRectangle({
      x: boxX,
      y: boxY,
      width: width / 2 - 50,
      height: 70,
      color: lightColor,
      borderColor: borderLight,
      borderWidth: 1,
    });

    page.drawText(kpi.label, {
      x: boxX + 15,
      y: boxY + 45,
      size: 9,
      font: boldFont,
      color: rgb(0.4, 0.4, 0.4),
    });

    page.drawText(kpi.value, {
      x: boxX + 15,
      y: boxY + 15,
      size: 16,
      font: boldFont,
      color: primaryColor,
    });

    if (!isLeft) kpiY -= 85;
  }

  // Top Selling Items Table
  let tableY = height - 420;
  page.drawText('TOP POPULAR MENU ITEMS', {
    x: 40,
    y: tableY + 20,
    size: 12,
    font: boldFont,
    color: darkColor,
  });

  // Table Headers
  page.drawRectangle({
    x: 40,
    y: tableY - 10,
    width: width - 80,
    height: 25,
    color: darkColor,
  });

  page.drawText('ITEM NAME', { x: 50, y: tableY - 1, size: 9, font: boldFont, color: rgb(1, 1, 1) });
  page.drawText('QTY SOLD', { x: width - 200, y: tableY - 1, size: 9, font: boldFont, color: rgb(1, 1, 1) });
  page.drawText('REVENUE CONTRIBUTION', { x: width - 120, y: tableY - 1, size: 9, font: boldFont, color: rgb(1, 1, 1) });

  const popularItems = data.popularItems || [];
  tableY -= 10;
  
  if (popularItems.length === 0) {
    tableY -= 30;
    page.drawText('No menu order events captured in this reporting interval.', {
      x: 50,
      y: tableY,
      size: 10,
      font: regularFont,
      color: rgb(0.5, 0.5, 0.5),
    });
  } else {
    popularItems.forEach((item: any, idx: number) => {
      tableY -= 30;
      // Zebra striping
      if (idx % 2 === 0) {
        page.drawRectangle({
          x: 40,
          y: tableY - 5,
          width: width - 80,
          height: 28,
          color: lightColor,
        });
      }
      
      page.drawText(item.name || 'Unknown Item', { x: 50, y: tableY + 5, size: 10, font: regularFont, color: darkColor });
      page.drawText(String(item.quantity || 0), { x: width - 180, y: tableY + 5, size: 10, font: regularFont, color: darkColor });
      page.drawText(`INR ${(item.revenue || 0).toLocaleString('en-IN')}`, { x: width - 110, y: tableY + 5, size: 10, font: boldFont, color: darkColor });
    });
  }

  // Footer Signoff
  page.drawText('Generated by ScanBite B2B Multi-Tenant SaaS Platform', {
    x: 40,
    y: 30,
    size: 8,
    font: regularFont,
    color: rgb(0.6, 0.6, 0.6),
  });

  return await pdfDoc.save();
}
